<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="CustomerManagementServiceWrapperWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/CustomerManagementServiceWrapperWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/CustomerManagementServiceWrapperWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://soap.aic.infosys.tuwien.ac.at/">
    <import location="CustomerManagementServiceWrapper.wsdl" namespace="http://soap.aic.infosys.tuwien.ac.at/"/>
    <plnk:partnerLinkType name="CustomerManagementServiceWrapperLinkType">
        <plnk:role name="CustomerManagementServiceWrapperRole" portType="ns:CustomerManagementServiceWrapper"/>
    </plnk:partnerLinkType>
</definitions>

