<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="WarehouseServiceImplService" targetNamespace="http://infosys.tuwien.ac.at/aic10/dto/warehouse" xmlns:ns1="http://soap.aic.infosys.tuwien.ac.at/" xmlns:ns2="http://cxf.apache.org/bindings/xformat" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://infosys.tuwien.ac.at/aic10/dto/warehouse" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="Warehouse.wsdl" namespace="http://soap.aic.infosys.tuwien.ac.at/"/>
  <wsdl:binding name="WarehouseServiceImplServiceSoapBinding" type="ns1:WarehouseService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="order">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="order">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="orderResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="check_availability">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="check_availability">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="check_availabilityResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WarehouseServiceImplService">
    <wsdl:port binding="tns:WarehouseServiceImplServiceSoapBinding" name="WarehousePT">
      <soap:address location="http://localhost:8080/Warehouse"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>