<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Supplier1Wrapper" targetNamespace="http://enterprise.netbeans.org/bpel/Supplier1Wrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/Supplier1Wrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://soap.aic.infosys.tuwien.ac.at/">
    <import location="Supplier1.wsdl" namespace="http://infosys.tuwien.ac.at/aic10/dto/supplier"/>
    <import location="http://localhost:8080/Supplier1?wsdl=SupplierService.wsdl" namespace="http://soap.aic.infosys.tuwien.ac.at/"/>
    <plnk:partnerLinkType name="SupplierServiceLinkType">
        <plnk:role name="SupplierServiceRole" portType="ns:SupplierService"/>
    </plnk:partnerLinkType>
</definitions>

